### ISSUE TITLE
Unable to pass options to fetch without using dedupeOptions as well

### ISSUE THREAD

**Issue by kanzelm3** [jmeas/fetch-dedupe#34]
Nice library, it is very convenient and simple to use.

I did find one minor issue, however, with the logic to handle init and dedupeOptions. I think [this line](https://github.com/jamesplease/fetch-dedupe/blob/master/src/index.js#L53) should actually be `initToUse = init` because this basically is the condition where you have confirmed that `dedupeOptions` were not set, and the `init` param is not actually the `dedupeOptions` (`init && init.responseType`) so the fallback should assume that `init` is the options the user expected to pass the fetch.

Currently, the logic instead sets `initToUse` equal to an empty object, therefore you cannot pass options to fetch without including `dedupeOptions` as well.

**Comment by jamesplease** [comment]
Thanks for the report, @kanzelm3 ! Would you have time to open a PR?

**Comment by kanzelm3** [comment]
Sure, I can probably get one up later tonight.

**Comment by jamesplease** [comment]
Thank you!

**Comment by kanzelm3** [comment]
@jamesplease I have added a couple PRs for your review.

**Comment by jamesplease** [comment]
Resolved in 2.1.1. Sorry again for the delay, @kanzelm3 ...dunno how this one slipped past me 🙈
